<?xml version="1.0" encoding="UTF-8"?>
<!-- Mit XMLSpy v2021 (x64) (http://www.altova.com) von Company="Informationstechnikzentrum Bund (ITZBund) (Informationstechnikzentrum Bund (ITZBund)) bearbeitet -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:fmpers="http://www.itzbund.de/MiKaDiv/FMPers/1.02"
  xmlns:std="http://www.itzbund.de/MiKaDiv/FMStd/1.02"
  xmlns:fmfach="http://www.itzbund.de/MiKaDiv/FMFach/1.02" targetNamespace="http://www.itzbund.de/MiKaDiv/FMFach/1.02" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:import namespace="http://www.itzbund.de/MiKaDiv/FMStd/1.02" schemaLocation="./MiKaDiv_FM_Standardtypen_1.02.xsd"/>
  <xs:import namespace="http://www.itzbund.de/MiKaDiv/FMPers/1.02" schemaLocation="./MiKaDiv_FM_Personentypen_1.02.xsd"/>
  <!-- Verwahrkette -->
  <xs:simpleType name="KnotenpositionType">
    <xs:annotation>
      <xs:documentation>Nicht negativer, numerischer Ganzzahlwert zur Angabe von Positionen in einer Verwahrkette.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:maxInclusive value="24"/>
      <xs:minInclusive value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="KnotenpositionDepotType">
    <xs:annotation>
      <xs:documentation>Nicht negativer, numerischer Ganzzahlwert zur Angabe von Knotenpositionen der depotführende Verwahrstelle.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:int">
      <xs:maxInclusive value="25"/>
      <xs:minInclusive value="2"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="AuszahlendeStellePositionType">
    <xs:annotation>
      <xs:documentation>Typ für die auszahlende Stelle innerhalb einer Verwahrkette an Position 1.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmpers:PersonVerwahrstelleType">
        <xs:attribute name="Position" type="xs:int" fixed="1">
          <xs:annotation>
            <xs:documentation>Position innerhalb der Verwahrkette; auszahlende Stelle ist immer an Position 1.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="VerwahrstellePositionType">
    <xs:annotation>
      <xs:documentation>Typ für eine Verwahrstelle innerhalb einer Verwahrkette.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmpers:PersonVerwahrstelleType">
        <xs:attribute name="Position" type="fmfach:KnotenpositionType" use="required">
          <xs:annotation>
            <xs:documentation>Position innerhalb der Verwahrkette. Muss eindeutig innerhalb der Kette sein.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="DepotfuehrendeStellePositionType">
    <xs:annotation>
      <xs:documentation>Typ für die depotführende Verwahrstelle innerhalb einer Verwahrkette (immer an der letzten Position).</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmpers:PersonDepotfuehrendeStelleType">
        <xs:attribute name="Position" type="fmfach:KnotenpositionDepotType" use="required">
          <xs:annotation>
            <xs:documentation>Position innerhalb der Verwahrkette, depotführende Verwahrstelle ist immer an letzter Position.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="VerwahrketteType">
    <xs:annotation>
      <xs:documentation>Typ zur Angabe einer Verwahrkette mit Constraint zur Sicherstellung, dass keine Position doppelt angegeben wurde.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="AuszahlendeStelle" type="fmfach:AuszahlendeStellePositionType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Angabe der auszahlenden Stelle in ihrer Position als Beginn der Verwahrkette.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Verwahrstelle" type="fmfach:VerwahrstellePositionType" minOccurs="0" maxOccurs="23">
        <xs:annotation>
          <xs:documentation>Angabe aller eingebundener inländischer und ausländischer (Zwischen)Verwahrstellen außer der auszahlenden Stelle.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="DepotfuehrendeStelle" type="fmfach:DepotfuehrendeStellePositionType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Angabe der depotführenden Verwahrstelle.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="AuszahlStelleIstDepotfuehrStelle" type="xs:boolean" default="false">
      <xs:annotation>
      </xs:annotation>
    </xs:attribute>

  </xs:complexType>
  <!-- Wertpapiere -->
  <xs:complexType name="WertpapiergattungType">
    <xs:annotation>
      <xs:documentation>Typ für eine Wertpapiergattung.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Bezeichnung" type="std:Name105Type" use="required">
      <xs:annotation>
        <xs:documentation>Bezeichnung der Wertpapiergattung.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="ISIN" type="std:ISINType" use="required">
      <xs:annotation>
        <xs:documentation>Internationale Wertpapierkennnummer der Wertpapiergattung.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <!-- Hinterlegungsschein; Heading G-->
  <xs:complexType name="HinterlegungsscheinType">
    <xs:annotation>
      <xs:documentation>Typ mit Informationen zum Hinterlegungsschein.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Wertpapier" type="fmfach:WertpapiergattungType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Das für den Hinterlegungsschein hinterlegte Wertpapier.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="Hinterlegungsstelle" type="fmpers:HinterlegungsstelleType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Die Hinterlegungsstelle ist nur anzugeben, wenn HinterlegungsstelleMelder unwahr ist.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="HinterlegungsstelleMelder" type="xs:boolean" default="true">
      <xs:annotation>
        <xs:documentation>Wenn HinterlegungsstelleMelder wahr ist, darf das Element "Hinterlegungsstelle" nicht angegeben werden. Wenn False, muss "Hinterlegungsstelle" angegeben werden.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Verhaeltnis" type="std:VerhaeltnisType" use="required">
      <xs:annotation>
        <xs:documentation>Das in den Emissionsbedingungen des Hinterlegungsscheines (1-Seite) festgelegte Verhältnis der Hinterlegungsscheine zu den durch die inländische Hinterlegungsstelle verwahrten inländischen Wertpapieren (x-Seite, hier anzugeben).</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="HinterlegungsscheineGesamtzahl" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Gesamtzahl ausgegebener Hinterlegungsscheine zum Zeitpunkt des Gewinnverteilungsbeschlusses.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="WertpapiereGesamtzahl" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Gesamtzahl hinterlegter Wertpapiere zum Zeitpunkt des Gewinnverteilungsbeschlusses.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="AnzahlHinterlegungsscheineGlaeubiger" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Anzahl der Hinterlegungsscheine des Gläubigers der Kapitalerträge (der Steuerbescheinigung) zum Zeitpunkt des Gewinnverteilungsbeschlusses.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="RecordTag" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Zeitpunkt des zweiten auf den Tag der Hauptversammlung folgenden Geschäftstages.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <!-- Ertrags und Steuertypen -->
  <xs:complexType name="SteuerangabenType">
    <xs:annotation>
      <xs:documentation>Typ zur Angabe von Steuern.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="Kapitalertragsteuer" type="std:Dezimal14dot2Type" use="required">
      <xs:annotation>
        <xs:documentation>Angaben zur Kapitalertragsteuer.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Solz" type="std:Dezimal14dot2Type" use="required">
      <xs:annotation>
        <xs:documentation>Angaben zum Solidaritätszuschlag.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="SteuerangabenMitSteuersatzUndRechtsgrundlageType">
    <xs:annotation>
      <xs:documentation>Typ für einen Steuerbetrag mit Angabe des angewendeten Steuersatzes sowie der Rechtsgrundlage für den angewendeten Steuersatz.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmfach:SteuerangabenType">
        <xs:attribute name="KapEStSteuersatz" type="std:SteuersatzType" use="required">
          <xs:annotation>
            <xs:documentation>Angewendeter Steuersatz auf Kapitalerträge.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="SolzSteuersatz" type="std:SteuersatzType" use="required">
          <xs:annotation>
            <xs:documentation>Angewendeter Steuersatz des Solidaritätszuschlags.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="KapEStRechtsgrundlage" type="std:RechtsgrundlageType" use="required">
          <xs:annotation>
            <xs:documentation>Rechtsgrundlage für den angewendeten Steuerabzug auf Kapitalerträge.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="GutschriftArtType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Bargeld">
        <xs:annotation>
          <xs:documentation>Bargeld</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Aktie">
        <xs:annotation>
          <xs:documentation>Aktie</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ErtragsGruppe45cType">
    <xs:annotation>
      <xs:documentation>Typ zur Angabe geforderter Erträge und Steuern für Meldungen nach § 45c Absatz 1 EStG.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="EinbehalteneSteuern" type="fmfach:SteuerangabenType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Liste aller einbehaltenen Steuern.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="BruttoBescheinigteSteuern" type="fmfach:SteuerangabenType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Liste aller Bruttobeträge bescheinigter Steuern.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="GemeldeteSteuern" type="fmfach:SteuerangabenType" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Liste aller gemeldeten Steuern.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Kapitalertrag" type="std:Dezimal14dot2Type" use="required">
      <xs:annotation>
        <xs:documentation>Bruttobetrag der erzielten Kapitalerträge.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Rechtsgrundlage" type="std:RechtsgrundlageType" use="required">
      <xs:annotation>
        <xs:documentation>Rechtsgrundlage für den angewendeten Steuersatz.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Stueckzahl" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Stückzahl der, von den Angaben betroffenen, Wertpapiere der Wertpapiergattung.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <!-- Handelstypen -->
  <xs:simpleType name="WertpapierhandelArtType">
    <xs:annotation>
      <xs:documentation>Typ zur Definition der Art des Wertpapierhandels.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="PO">
        <xs:annotation>
          <xs:documentation>Kauf</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="SO">
        <xs:annotation>
          <xs:documentation>Verkauf</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="DT">
        <xs:annotation>
          <xs:documentation>Übertrag</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="TL">
        <xs:annotation>
          <xs:documentation>Übertragung wegen Wertpapierleihe.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RL">
        <xs:annotation>
          <xs:documentation>Rückübertragung wegen Wertpapierleihe.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="TP">
        <xs:annotation>
          <xs:documentation>Übertragung wegen Wertpapierpensionsgeschäft.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="RP">
        <xs:annotation>
          <xs:documentation>Rückübertragung wegen Wertpapierpensionsgeschäft.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="WertpapierArtType">
    <xs:annotation>
      <xs:documentation>Typ zur Definition der Art des Wertpapieres.</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Aktie">
        <xs:annotation>
          <xs:documentation>Aktie</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Anleihe">
        <xs:annotation>
          <xs:documentation>Anleihe</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="Aktienzertifikat">
        <xs:annotation>
          <xs:documentation>Aktienzertifikat (Hinterlegungsschein).</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="StueckzahlenType">
    <xs:annotation>
      <xs:documentation>Typ für Angaben zu dem Kapitalertrag zugrundeliegenden Wertpapieren nach § 45b Absatz 2 Nr. 5 a) und b) EStG.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="StueckzahlMehrAls5Tage" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Die Anzahl der Aktien, die mehr als fünf Tage vor dem auf den Tag der Hauptversammlung folgenden Geschäftstag erworben wurden.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlInnerhalbVon5Tagen" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Die Anzahl der Aktien, die innerhalb dieses Zeitraumes erworben wurden.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlMitFinanzvereinbarung" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Die Anzahl der Aktien, die mit einer Finanzvereinbarung verbunden sind. Bei Inanspruchnahme der Nichtbeanstandungsregel aus Rz 8 des BMF-Schreibens Einzelfragen zur Datenübermittlung nach Maßgabe des § 45b und § 45c EStG ist der Wert “0“ zu erfassen.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlOhneFinanzvereinbarung" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Die Anzahl der Aktien, die mit einer Finanzvereinbarung verbunden sind. Bei Inanspruchnahme der Nichtbeanstandungsregel aus Rz 8 des BMF-Schreibens Einzelfragen zur Datenübermittlung nach Maßgabe des § 45b und § 45c EStG ist der Wert “0“ zu erfassen.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="WertpapierhandelType">
    <xs:annotation>
      <xs:documentation>Informationen über getätigte Wertpapierhandel.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="StueckzahlTransaktion" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Stückzahl Transaktion</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Handelstag" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Handelstag</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="VereinbarterAbwicklungstag" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Vereinbarter Abwicklungstag</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="TatsaechlicherAbwicklungstag" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Tatsächlicher Abwicklungstag</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Art" type="fmfach:WertpapierhandelArtType" use="required">
      <xs:annotation>
        <xs:documentation>Art des getätigten Wertpapierhandels.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlZuordnungWertpapierleihe" type="std:WertpapierStueckzahlType" use="optional">
      <xs:annotation>
        <xs:documentation>Stückzahl der Zuordnung zu einer Wertpapierleihe.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlZuordnungWertpapierpensionsgeschaeft" type="std:WertpapierStueckzahlType" use="optional">
      <xs:annotation>
        <xs:documentation>Stückzahl der Zuordnung zu einem Wertpapierpensionsgeschäft.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="ZugangslisteType">
    <xs:sequence>
      <xs:element name="Zugang" type="fmfach:WertpapierhandelType" minOccurs="1" maxOccurs="1000">
        <xs:annotation>
          <xs:documentation>Informationen über angeschaffte / übertragene Wertpapiere. Die Position (Verleiher oder Entleiher), die der Gläubiger beim Handel eingenommen hat, ist maßgeblich entscheidend dafür, ob eine Wertpapierleihe [/ Wertpapierpensionsgeschäft] ein Zugang oder ein Abgang ist. Hat ein Gläubiger am Handelstag Wertpapiere verliehen oder zurückgegeben, so handelt es sich um einen Abgang. Hat er Wertpapiere nach einer Leihe zurückbekommen oder sich diese am Handelstag ausgeliehen, so handelt es sich um einen Zugang.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="WeitereVorhanden" type="xs:boolean" default="false">
      <xs:annotation>
        <xs:documentation>Wenn mehr Zugänge vorhanden sind, als in der Meldung maximal angegeben werden können, so ist dieses Flag auf "true" zu setzen.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlWertpapierleihe" type="std:WertpapierStueckzahlType" use="optional">
      <xs:annotation>
        <xs:documentation>Stückzahl Wertpapierleihe</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="StueckzahlWertpapierpensionsgeschaeft" type="std:WertpapierStueckzahlType" use="optional">
      <xs:annotation>
        <xs:documentation>Stückzahl Wertpapierpensionsgeschäft</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <xs:complexType name="AbgangslisteType">
    <xs:sequence>
      <xs:element name="Abgang" type="fmfach:WertpapierhandelType" minOccurs="1" maxOccurs="1000">
        <xs:annotation>
          <xs:documentation>Informationen über Wertpapiere, die innerhalb von 47 Tagen nach dem Tag der Hauptversammlung der Kapitalerträge veräußert, verliehen oder rückübertragen wurden. Die Position (Verleiher oder Entleiher), die der Gläubiger beim Handel eingenommen hat, ist maßgeblich dafür, ob eine Wertpapierleihe [/ Wertpapierpensionsgeschäft] ein Zugang oder ein Abgang ist. Hat ein Gläubiger am Handelstag Wertpapiere verliehen oder zurückgegeben, so handelt es sich um einen Abgang. Hat er Wertpapiere nach einer Leihe zurückbekommen oder sich diese am Handelstag ausgeliehen, so handelt es sich um einen Zugang.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="WeitereVorhanden" type="xs:boolean" default="false">
      <xs:annotation>
        <xs:documentation>Wenn mehr Abgänge vorhanden sind, als in der Meldung maximal angegeben werden können, so ist dieses Flag auf "true" zu setzen.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>
  <!-- Zahlungstage -->
  <xs:complexType name="KapitalertragType">
    <xs:annotation>
      <xs:documentation>Typ für einen einzelnen Kapitalertrag.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="EinbehalteneSteuern" type="fmfach:SteuerangabenMitSteuersatzUndRechtsgrundlageType" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Liste aller einbehaltenen Steuern.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="KontonummerGutschrift" type="std:KontonummerType" use="required">
      <xs:annotation>
        <xs:documentation>Nummer des Kontos, auf dem die Dividendenzahlung des Anlegers durch sein depotführendes Institut gutgeschrieben wurde.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="GutschriftArt" type="fmfach:GutschriftArtType" use="required">
      <xs:annotation>
        <xs:documentation>Die Art der Gutschrift.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Stueckzahl" type="std:WertpapierStueckzahlType" use="required">
      <xs:annotation>
        <xs:documentation>Stückzahl der Wertpapiere, die dem Kapitalertrag zugrunde liegen.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KapitalertragBrutto" type="std:Dezimal14dot2Type" use="required">
      <xs:annotation>
        <xs:documentation>Bruttobetrag der erzielten Kapitalerträge.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="KapitalertragNetto" type="std:Dezimal14dot2Type" use="required">
      <xs:annotation>
        <xs:documentation>Nettobetrag der erzielten Kapitalerträge.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="PaymentlineBasisType" abstract="true">
    <xs:annotation>
      <xs:documentation>Abstrakter Typ für eine einzelne Paymentline.</xs:documentation>
    </xs:annotation>
    <xs:attribute name="ISIN" type="std:ISINType" use="required">
      <xs:annotation>
        <xs:documentation>Internationale Wertpapierkennnummer der Wertpapiergattung.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
    <xs:attribute name="Zahlungstag" type="xs:date" use="required">
      <xs:annotation>
        <xs:documentation>Zahlungstag.</xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Paymentline45BBasisType" abstract="true">
    <xs:annotation>
      <xs:documentation>Abstrakter Typ für eine einzelne Paymentline in Meldeart 11, 13 oder ERG.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmfach:PaymentlineBasisType">
        <xs:sequence>
          <xs:element name="AusschuettendeGesellschaft" type="fmpers:AusschuettendeGesellschaftType" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Ausschüttende Gesellschaft.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="ArtDesWertpapieres" type="fmfach:WertpapierArtType">
          <xs:annotation>
            <xs:documentation>Art des Wertpapieres.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
        <xs:attribute name="COAF" use="required">
          <xs:annotation>
            <xs:documentation>Corporate Action Event Reference.</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="std:NameType">
              <xs:minLength value="1"/>
              <xs:maxLength value="16"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="PaymentlineListeMa11ErgType">
    <xs:annotation>
      <xs:documentation>Typ für eine Liste von Paymentlines in den Meldearten 11 oder ERG.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Paymentline" type="fmfach:PaymentlineMa11ErgType" minOccurs="1" maxOccurs="1000"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PaymentlineMa11ErgType">
    <xs:annotation>
      <xs:documentation>Erweiterung des Basistyps um den meldeartspezifischen Zahlungstag.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fmfach:Paymentline45BBasisType">
        <xs:sequence>
          <xs:element name="ZusatzMeldungUUID" type="std:UUIDType" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>UUID der Zusatzangabenmeldung mit Angaben zu Zu- und Abgängen, die Teil dieser Meldung ist.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Kapitalertrag" type="fmfach:KapitalertragType" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>§ 45b Absatz 2 Nr. 4 EStG (Heading D).</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Stueckzahlen" type="fmfach:StueckzahlenType" minOccurs="1" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>Angaben zu § 45b Absatz 2 Nr. 5 a) und b) EStG.</xs:documentation>
            </xs:annotation>
          </xs:element>
          <xs:element name="Hinterlegungsschein" type="fmfach:HinterlegungsscheinType" minOccurs="0" maxOccurs="1">
            <xs:annotation>
              <xs:documentation>§ 45b Absatz 2 Nr. 6 EStG (Heading G); Darf nur angegeben werden, wenn Nichtbeanstandung-45b-Abs.2-Nr.6 false ist.</xs:documentation>
            </xs:annotation>
          </xs:element>
        </xs:sequence>
        <xs:attribute name="Nichtbeanstandung-45b-Abs.2-Nr.6" type="xs:boolean" default="false">
          <xs:annotation>
            <xs:documentation>Kennzeichnung, dass die Nichtbeanstandungsregelung zum 2. Steuerabzug aus der Rz 70 des BMF-Schreibens zu Einzelfragen zur Datenübermittlung nach Maßgabe des § 45b und des § 45c EStG angewendet wurde.</xs:documentation>
          </xs:annotation>
        </xs:attribute>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

</xs:schema>
